import React from 'react';
import { Link } from 'react-router-dom';
import { motion, useReducedMotion } from 'framer-motion';
import {
  SparklesIcon,
  ClockIcon,
  ChartBarIcon,
  DevicePhoneMobileIcon,
} from '@heroicons/react/24/outline';
import { Button } from '../components/ui/Button';
import { fadeUp } from '../utils/animations';

/**
 * LandingPage
 * - Modern hero with glass demo card to preview AI workout output
 * - Reduced-motion aware animations
 * - Streamlined containers + semantic landmarks
 * - Accessible, keyboard-friendly, and dark-mode ready
 */

type Feature = {
  name: string;
  description: string;
  icon: React.ComponentType<React.ComponentProps<'svg'>>;
};

const features: Feature[] = [
  {
    name: 'AI-Powered Workouts',
    description:
      'Personalized plans generated by an engine that learns from your progress, preferences, and available equipment.',
    icon: SparklesIcon,
  },
  {
    name: 'Adaptive Training',
    description:
      'Sessions evolve automatically—adjusting difficulty, volume, and focus to keep you progressing.',
    icon: ChartBarIcon,
  },
  {
    name: 'Time Efficient',
    description:
      'Hyper-focused programming that fits your schedule without sacrificing results.',
    icon: ClockIcon,
  },
  {
    name: 'Mobile First',
    description:
      'A seamless experience across devices, with offline support for when you’re on the move.',
    icon: DevicePhoneMobileIcon,
  },
];



const FeatureCard: React.FC<{ feature: Feature; index: number }> = ({ feature, index }) => (
  <motion.div
    variants={fadeUp(index * 0.05)}
    initial="initial"
    animate="animate"
    viewport={{ once: true, margin: '-20% 0px -20% 0px' }}
    className="group relative rounded-2xl border border-black/5 bg-white/70 backdrop-blur-md p-6 shadow-sm hover:shadow-lg transition-shadow"
  >
    <div className="mb-4 inline-flex h-12 w-12 items-center justify-center rounded-xl bg-primary-100">
      <feature.icon className="h-6 w-6 text-primary-600" aria-hidden="true" />
    </div>
    <h3 className="text-lg font-semibold text-gray-900">{feature.name}</h3>
    <p className="mt-2 text-gray-600">{feature.description}</p>

    {/* Subtle hover halo */}
    <div
      aria-hidden="true"
      className="pointer-events-none absolute inset-0 rounded-2xl opacity-0 group-hover:opacity-100 transition-opacity"
      style={{
        boxShadow:
          '0 0 0 1px rgba(59,130,246,0.10), 0 10px 30px rgba(59,130,246,0.10), inset 0 0 40px rgba(59,130,246,0.06)',
      }}
    />
  </motion.div>
);



export const LandingPage: React.FC = () => {
  const reduceMotion = useReducedMotion();

  return (
    <div className="min-h-screen bg-white relative overflow-hidden">
      {/* Skip link for keyboard users */}
      <a
        href="#main"
        className="sr-only focus:not-sr-only focus:fixed focus:top-4 focus:left-4 focus:z-50 focus:rounded-2xl focus:bg-primary-600 focus:text-white focus:px-4 focus:py-2 focus:text-sm focus:shadow-lg focus:font-semibold"
      >
        Skip to content
      </a>

      {/* Decorative background */}
      <div className="absolute inset-0" aria-hidden="true">
        <div className="absolute inset-0 bg-mesh-gradient opacity-20" />
        <motion.div
          animate={
            reduceMotion
              ? { opacity: 0.12, scale: 1 }
              : { scale: [1, 1.18, 1], opacity: [0.08, 0.22, 0.08] }
          }
          transition={reduceMotion ? { duration: 0 } : { duration: 8, repeat: Infinity, ease: 'easeInOut' }}
          className="absolute top-1/4 left-1/4 w-96 h-96 bg-gradient-energy rounded-full blur-3xl"
        />
        <motion.div
          animate={
            reduceMotion
              ? { opacity: 0.14, scale: 1 }
              : { scale: [1.1, 0.92, 1.1], opacity: [0.12, 0.28, 0.12] }
          }
          transition={reduceMotion ? { duration: 0 } : { duration: 6, repeat: Infinity, ease: 'easeInOut', delay: 2 }}
          className="absolute bottom-1/4 right-1/4 w-80 h-80 bg-gradient-success rounded-full blur-3xl"
        />
      </div>

      {/* Hero */}
      <header className="relative z-10">
        <div className="mx-auto max-w-7xl px-4 sm:px-6 lg:px-8 pt-20 pb-12 md:pt-28 md:pb-20">
          <motion.div
            variants={fadeUp()}
            initial="initial"
            animate="animate"
            className="text-center"
          >
            <div className="inline-flex items-center px-5 py-2.5 rounded-full bg-neutral-100 border border-neutral-200 text-neutral-700 text-sm font-semibold mb-7 shadow-sm">
              <SparklesIcon className="w-4 h-4 mr-2 text-energy-500" aria-hidden="true" />
              <span className="bg-gradient-energy bg-clip-text text-transparent">
                AI‑Powered Fitness, Personalized
              </span>
              <span className="ml-2 inline-flex h-2 w-2 rounded-full bg-energy-500 animate-pulse" aria-hidden="true" />
            </div>

            <h1 className="text-5xl md:text-7xl lg:text-8xl font-display font-bold text-neutral-900 leading-tight tracking-tight">
              Your AI Fitness
              <br />
              <span className="bg-gradient-energy bg-clip-text text-transparent">
                Revolution
              </span>
            </h1>

            <p className="mt-6 text-lg md:text-xl text-neutral-600 mx-auto max-w-3xl leading-relaxed">
              Transform your training with{' '}
              <span className="font-semibold bg-gradient-energy bg-clip-text text-transparent">adaptive workouts</span>{' '}
              tuned to your goals, schedule, and equipment—evolving automatically as you do.
            </p>

            <div className="mt-10 flex flex-col sm:flex-row gap-4 justify-center">
              <Link to="/signup" aria-label="Create your free NeuraFit account">
                <Button variant="energy" size="lg" className="text-lg px-8 py-4 font-semibold">
                  Start Your Journey
                </Button>
              </Link>
              <Link to="/login" aria-label="Sign in to NeuraFit">
                <Button variant="secondary" size="lg" className="text-lg px-8 py-4 font-semibold">
                  Sign In
                </Button>
              </Link>
            </div>
          </motion.div>

          {/* Value proposition */}
          <motion.div
            variants={fadeUp(0.25)}
            initial="initial"
            animate="animate"
            className="mt-12 md:mt-16 text-center max-w-3xl mx-auto"
          >
            <h2 className="text-2xl md:text-3xl font-bold text-neutral-900">
              Smarter plans. Better adherence. Real progress.
            </h2>
            <p className="mt-3 text-neutral-600">
              NeuraFit removes guesswork: the right movements, rep schemes, and rest—auto‑calibrated
              to your performance and recovery signals. Train with intent, not intuition.
            </p>
          </motion.div>
        </div>
      </header>

      <main id="main" className="relative z-10">
        {/* Features */}
        <section id="features" className="py-20 bg-gray-50">
          <div className="mx-auto max-w-7xl px-4 sm:px-6 lg:px-8">
            <motion.div
              variants={fadeUp()}
              initial="initial"
              animate="animate"
              viewport={{ once: true }}
              className="text-center mb-14"
            >
              <h2 className="text-3xl md:text-4xl font-bold text-gray-900">
                Why Choose NeuraFit?
              </h2>
              <p className="mt-3 text-lg text-gray-600 max-w-2xl mx-auto">
                Experience the future of fitness with personalization that makes every minute count.
              </p>
            </motion.div>

            <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-4 gap-6 lg:gap-8">
              {features.map((f, i) => (
                <FeatureCard key={f.name} feature={f} index={i} />
              ))}
            </div>
          </div>
        </section>

        {/* CTA */}
        <section className="py-20 bg-white">
          <div className="mx-auto max-w-4xl text-center px-4 sm:px-6 lg:px-8">
            <motion.div
              variants={fadeUp()}
              initial="initial"
              animate="animate"
              viewport={{ once: true }}
            >
              <h2 className="text-3xl md:text-4xl font-bold text-gray-900">
                Ready to Transform Your Fitness?
              </h2>
              <p className="mt-3 text-lg text-gray-600">
                Join athletes, creators, and busy professionals training with AI‑guided precision.
              </p>
              <div className="mt-8 flex justify-center">
                <Link to="/signup">
                  <Button size="lg" className="px-8 py-4 text-lg" variant="energy">
                    Get Started Free
                  </Button>
                </Link>
              </div>
            </motion.div>
          </div>
        </section>
      </main>
    </div>
  );
};